# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends anonymous usage statistics to help improve CocoaPods.
# You can disable this by running:
# pod install --no-analytics

target 'Runner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'cloud_firestore'

  # Flutter-specific pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end
